name: Update index.html

on:
  push:
    paths:
      - 'ctx_files/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python generate_index.py
      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add index.html
          git commit -m "auto-update index" || echo "No changes"
          git push